// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.bitty.proto;

public final class Broker {
  private Broker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bitty.proto.MessageFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool isRequest = 1;</code>
     * @return The isRequest.
     */
    boolean getIsRequest();

    /**
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    int getCmdValue();
    /**
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
     * @return The cmd.
     */
    com.bitty.proto.Broker.MessageFrame.Cmd getCmd();

    /**
     * <code>int32 reqId = 3;</code>
     * @return The reqId.
     */
    int getReqId();

    /**
     * <pre>
     *请求内容
     * </pre>
     *
     * <code>bytes payload = 4;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code com.bitty.proto.MessageFrame}
   */
  public  static final class MessageFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bitty.proto.MessageFrame)
      MessageFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageFrame.newBuilder() to construct.
    private MessageFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageFrame() {
      cmd_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageFrame();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageFrame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isRequest_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 24: {

              reqId_ = input.readInt32();
              break;
            }
            case 34: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bitty.proto.Broker.internal_static_com_bitty_proto_MessageFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bitty.proto.Broker.internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bitty.proto.Broker.MessageFrame.class, com.bitty.proto.Broker.MessageFrame.Builder.class);
    }

    /**
     * Protobuf enum {@code com.bitty.proto.MessageFrame.Cmd}
     */
    public enum Cmd
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      /**
       * <code>ERROR = 99;</code>
       */
      ERROR(99),
      /**
       * <code>resolveNode = 1;</code>
       */
      resolveNode(1),
      /**
       * <code>resolveUser = 2;</code>
       */
      resolveUser(2),
      /**
       * <code>status = 3;</code>
       */
      status(3),
      /**
       * <pre>
       **
       *下线
       * </pre>
       *
       * <code>DOWN = 4;</code>
       */
      DOWN(4),
      /**
       * <pre>
       **
       *上线
       * </pre>
       *
       * <code>Up = 5;</code>
       */
      Up(5),
      /**
       * <pre>
       **
       *转发消息
       * </pre>
       *
       * <code>Forward = 6;</code>
       */
      Forward(6),
      /**
       * <pre>
       **
       *注册broker
       * </pre>
       *
       * <code>signup = 7;</code>
       */
      signup(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;
      /**
       * <code>ERROR = 99;</code>
       */
      public static final int ERROR_VALUE = 99;
      /**
       * <code>resolveNode = 1;</code>
       */
      public static final int resolveNode_VALUE = 1;
      /**
       * <code>resolveUser = 2;</code>
       */
      public static final int resolveUser_VALUE = 2;
      /**
       * <code>status = 3;</code>
       */
      public static final int status_VALUE = 3;
      /**
       * <pre>
       **
       *下线
       * </pre>
       *
       * <code>DOWN = 4;</code>
       */
      public static final int DOWN_VALUE = 4;
      /**
       * <pre>
       **
       *上线
       * </pre>
       *
       * <code>Up = 5;</code>
       */
      public static final int Up_VALUE = 5;
      /**
       * <pre>
       **
       *转发消息
       * </pre>
       *
       * <code>Forward = 6;</code>
       */
      public static final int Forward_VALUE = 6;
      /**
       * <pre>
       **
       *注册broker
       * </pre>
       *
       * <code>signup = 7;</code>
       */
      public static final int signup_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Cmd valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Cmd forNumber(int value) {
        switch (value) {
          case 0: return PING;
          case 99: return ERROR;
          case 1: return resolveNode;
          case 2: return resolveUser;
          case 3: return status;
          case 4: return DOWN;
          case 5: return Up;
          case 6: return Forward;
          case 7: return signup;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Cmd> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
              public Cmd findValueByNumber(int number) {
                return Cmd.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.bitty.proto.Broker.MessageFrame.getDescriptor().getEnumTypes().get(0);
      }

      private static final Cmd[] VALUES = values();

      public static Cmd valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Cmd(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.bitty.proto.MessageFrame.Cmd)
    }

    public static final int ISREQUEST_FIELD_NUMBER = 1;
    private boolean isRequest_;
    /**
     * <code>bool isRequest = 1;</code>
     * @return The isRequest.
     */
    public boolean getIsRequest() {
      return isRequest_;
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
     * @return The cmd.
     */
    public com.bitty.proto.Broker.MessageFrame.Cmd getCmd() {
      @SuppressWarnings("deprecation")
      com.bitty.proto.Broker.MessageFrame.Cmd result = com.bitty.proto.Broker.MessageFrame.Cmd.valueOf(cmd_);
      return result == null ? com.bitty.proto.Broker.MessageFrame.Cmd.UNRECOGNIZED : result;
    }

    public static final int REQID_FIELD_NUMBER = 3;
    private int reqId_;
    /**
     * <code>int32 reqId = 3;</code>
     * @return The reqId.
     */
    public int getReqId() {
      return reqId_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    /**
     * <pre>
     *请求内容
     * </pre>
     *
     * <code>bytes payload = 4;</code>
     * @return The payload.
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isRequest_ != false) {
        output.writeBool(1, isRequest_);
      }
      if (cmd_ != com.bitty.proto.Broker.MessageFrame.Cmd.PING.getNumber()) {
        output.writeEnum(2, cmd_);
      }
      if (reqId_ != 0) {
        output.writeInt32(3, reqId_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(4, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isRequest_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isRequest_);
      }
      if (cmd_ != com.bitty.proto.Broker.MessageFrame.Cmd.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cmd_);
      }
      if (reqId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, reqId_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bitty.proto.Broker.MessageFrame)) {
        return super.equals(obj);
      }
      com.bitty.proto.Broker.MessageFrame other = (com.bitty.proto.Broker.MessageFrame) obj;

      if (getIsRequest()
          != other.getIsRequest()) return false;
      if (cmd_ != other.cmd_) return false;
      if (getReqId()
          != other.getReqId()) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRequest());
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Broker.MessageFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.MessageFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.MessageFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bitty.proto.Broker.MessageFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bitty.proto.MessageFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bitty.proto.MessageFrame)
        com.bitty.proto.Broker.MessageFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_MessageFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bitty.proto.Broker.MessageFrame.class, com.bitty.proto.Broker.MessageFrame.Builder.class);
      }

      // Construct using com.bitty.proto.Broker.MessageFrame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isRequest_ = false;

        cmd_ = 0;

        reqId_ = 0;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_MessageFrame_descriptor;
      }

      @java.lang.Override
      public com.bitty.proto.Broker.MessageFrame getDefaultInstanceForType() {
        return com.bitty.proto.Broker.MessageFrame.getDefaultInstance();
      }

      @java.lang.Override
      public com.bitty.proto.Broker.MessageFrame build() {
        com.bitty.proto.Broker.MessageFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bitty.proto.Broker.MessageFrame buildPartial() {
        com.bitty.proto.Broker.MessageFrame result = new com.bitty.proto.Broker.MessageFrame(this);
        result.isRequest_ = isRequest_;
        result.cmd_ = cmd_;
        result.reqId_ = reqId_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bitty.proto.Broker.MessageFrame) {
          return mergeFrom((com.bitty.proto.Broker.MessageFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bitty.proto.Broker.MessageFrame other) {
        if (other == com.bitty.proto.Broker.MessageFrame.getDefaultInstance()) return this;
        if (other.getIsRequest() != false) {
          setIsRequest(other.getIsRequest());
        }
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (other.getReqId() != 0) {
          setReqId(other.getReqId());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bitty.proto.Broker.MessageFrame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bitty.proto.Broker.MessageFrame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isRequest_ ;
      /**
       * <code>bool isRequest = 1;</code>
       * @return The isRequest.
       */
      public boolean getIsRequest() {
        return isRequest_;
      }
      /**
       * <code>bool isRequest = 1;</code>
       * @param value The isRequest to set.
       * @return This builder for chaining.
       */
      public Builder setIsRequest(boolean value) {
        
        isRequest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isRequest = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsRequest() {
        
        isRequest_ = false;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
       * @return The enum numeric value on the wire for cmd.
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
       * @param value The enum numeric value on the wire for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
       * @return The cmd.
       */
      public com.bitty.proto.Broker.MessageFrame.Cmd getCmd() {
        @SuppressWarnings("deprecation")
        com.bitty.proto.Broker.MessageFrame.Cmd result = com.bitty.proto.Broker.MessageFrame.Cmd.valueOf(cmd_);
        return result == null ? com.bitty.proto.Broker.MessageFrame.Cmd.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.bitty.proto.Broker.MessageFrame.Cmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int reqId_ ;
      /**
       * <code>int32 reqId = 3;</code>
       * @return The reqId.
       */
      public int getReqId() {
        return reqId_;
      }
      /**
       * <code>int32 reqId = 3;</code>
       * @param value The reqId to set.
       * @return This builder for chaining.
       */
      public Builder setReqId(int value) {
        
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reqId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqId() {
        
        reqId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *请求内容
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @return The payload.
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       *请求内容
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求内容
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bitty.proto.MessageFrame)
    }

    // @@protoc_insertion_point(class_scope:com.bitty.proto.MessageFrame)
    private static final com.bitty.proto.Broker.MessageFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bitty.proto.Broker.MessageFrame();
    }

    public static com.bitty.proto.Broker.MessageFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageFrame>
        PARSER = new com.google.protobuf.AbstractParser<MessageFrame>() {
      @java.lang.Override
      public MessageFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageFrame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bitty.proto.Broker.MessageFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface resolveNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bitty.proto.resolveNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
     * @return The enum numeric value on the wire for schema.
     */
    int getSchemaValue();
    /**
     * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
     * @return The schema.
     */
    com.bitty.proto.Broker.resolveNode.Schema getSchema();

    /**
     * <code>int32 node = 2;</code>
     * @return The node.
     */
    int getNode();

    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * <pre>
   **
   *查找节点
   * </pre>
   *
   * Protobuf type {@code com.bitty.proto.resolveNode}
   */
  public  static final class resolveNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bitty.proto.resolveNode)
      resolveNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use resolveNode.newBuilder() to construct.
    private resolveNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private resolveNode() {
      schema_ = 0;
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new resolveNode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private resolveNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              schema_ = rawValue;
              break;
            }
            case 16: {

              node_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 32: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bitty.proto.Broker.internal_static_com_bitty_proto_resolveNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bitty.proto.Broker.internal_static_com_bitty_proto_resolveNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bitty.proto.Broker.resolveNode.class, com.bitty.proto.Broker.resolveNode.Builder.class);
    }

    /**
     * Protobuf enum {@code com.bitty.proto.resolveNode.Schema}
     */
    public enum Schema
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TCP = 0;</code>
       */
      TCP(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TCP = 0;</code>
       */
      public static final int TCP_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Schema valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Schema forNumber(int value) {
        switch (value) {
          case 0: return TCP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Schema>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Schema> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Schema>() {
              public Schema findValueByNumber(int number) {
                return Schema.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.bitty.proto.Broker.resolveNode.getDescriptor().getEnumTypes().get(0);
      }

      private static final Schema[] VALUES = values();

      public static Schema valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Schema(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.bitty.proto.resolveNode.Schema)
    }

    public static final int SCHEMA_FIELD_NUMBER = 1;
    private int schema_;
    /**
     * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
     * @return The enum numeric value on the wire for schema.
     */
    public int getSchemaValue() {
      return schema_;
    }
    /**
     * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
     * @return The schema.
     */
    public com.bitty.proto.Broker.resolveNode.Schema getSchema() {
      @SuppressWarnings("deprecation")
      com.bitty.proto.Broker.resolveNode.Schema result = com.bitty.proto.Broker.resolveNode.Schema.valueOf(schema_);
      return result == null ? com.bitty.proto.Broker.resolveNode.Schema.UNRECOGNIZED : result;
    }

    public static final int NODE_FIELD_NUMBER = 2;
    private int node_;
    /**
     * <code>int32 node = 2;</code>
     * @return The node.
     */
    public int getNode() {
      return node_;
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (schema_ != com.bitty.proto.Broker.resolveNode.Schema.TCP.getNumber()) {
        output.writeEnum(1, schema_);
      }
      if (node_ != 0) {
        output.writeInt32(2, node_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(4, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (schema_ != com.bitty.proto.Broker.resolveNode.Schema.TCP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, schema_);
      }
      if (node_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, node_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bitty.proto.Broker.resolveNode)) {
        return super.equals(obj);
      }
      com.bitty.proto.Broker.resolveNode other = (com.bitty.proto.Broker.resolveNode) obj;

      if (schema_ != other.schema_) return false;
      if (getNode()
          != other.getNode()) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + schema_;
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bitty.proto.Broker.resolveNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Broker.resolveNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.resolveNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.resolveNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bitty.proto.Broker.resolveNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *查找节点
     * </pre>
     *
     * Protobuf type {@code com.bitty.proto.resolveNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bitty.proto.resolveNode)
        com.bitty.proto.Broker.resolveNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_resolveNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_resolveNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bitty.proto.Broker.resolveNode.class, com.bitty.proto.Broker.resolveNode.Builder.class);
      }

      // Construct using com.bitty.proto.Broker.resolveNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schema_ = 0;

        node_ = 0;

        ip_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_resolveNode_descriptor;
      }

      @java.lang.Override
      public com.bitty.proto.Broker.resolveNode getDefaultInstanceForType() {
        return com.bitty.proto.Broker.resolveNode.getDefaultInstance();
      }

      @java.lang.Override
      public com.bitty.proto.Broker.resolveNode build() {
        com.bitty.proto.Broker.resolveNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bitty.proto.Broker.resolveNode buildPartial() {
        com.bitty.proto.Broker.resolveNode result = new com.bitty.proto.Broker.resolveNode(this);
        result.schema_ = schema_;
        result.node_ = node_;
        result.ip_ = ip_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bitty.proto.Broker.resolveNode) {
          return mergeFrom((com.bitty.proto.Broker.resolveNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bitty.proto.Broker.resolveNode other) {
        if (other == com.bitty.proto.Broker.resolveNode.getDefaultInstance()) return this;
        if (other.schema_ != 0) {
          setSchemaValue(other.getSchemaValue());
        }
        if (other.getNode() != 0) {
          setNode(other.getNode());
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bitty.proto.Broker.resolveNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bitty.proto.Broker.resolveNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int schema_ = 0;
      /**
       * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
       * @return The enum numeric value on the wire for schema.
       */
      public int getSchemaValue() {
        return schema_;
      }
      /**
       * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
       * @param value The enum numeric value on the wire for schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchemaValue(int value) {
        schema_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
       * @return The schema.
       */
      public com.bitty.proto.Broker.resolveNode.Schema getSchema() {
        @SuppressWarnings("deprecation")
        com.bitty.proto.Broker.resolveNode.Schema result = com.bitty.proto.Broker.resolveNode.Schema.valueOf(schema_);
        return result == null ? com.bitty.proto.Broker.resolveNode.Schema.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
       * @param value The schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchema(com.bitty.proto.Broker.resolveNode.Schema value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        schema_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.resolveNode.Schema schema = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSchema() {
        
        schema_ = 0;
        onChanged();
        return this;
      }

      private int node_ ;
      /**
       * <code>int32 node = 2;</code>
       * @return The node.
       */
      public int getNode() {
        return node_;
      }
      /**
       * <code>int32 node = 2;</code>
       * @param value The node to set.
       * @return This builder for chaining.
       */
      public Builder setNode(int value) {
        
        node_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 node = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNode() {
        
        node_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 3;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 4;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 4;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bitty.proto.resolveNode)
    }

    // @@protoc_insertion_point(class_scope:com.bitty.proto.resolveNode)
    private static final com.bitty.proto.Broker.resolveNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bitty.proto.Broker.resolveNode();
    }

    public static com.bitty.proto.Broker.resolveNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<resolveNode>
        PARSER = new com.google.protobuf.AbstractParser<resolveNode>() {
      @java.lang.Override
      public resolveNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new resolveNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<resolveNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<resolveNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bitty.proto.Broker.resolveNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface signupNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bitty.proto.signupNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
     * @return The enum numeric value on the wire for schema.
     */
    int getSchemaValue();
    /**
     * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
     * @return The schema.
     */
    com.bitty.proto.Broker.signupNode.Schema getSchema();

    /**
     * <code>int32 node = 2;</code>
     * @return The node.
     */
    int getNode();

    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * <pre>
   **
   *注册节点
   * </pre>
   *
   * Protobuf type {@code com.bitty.proto.signupNode}
   */
  public  static final class signupNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bitty.proto.signupNode)
      signupNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use signupNode.newBuilder() to construct.
    private signupNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private signupNode() {
      schema_ = 0;
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new signupNode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private signupNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              schema_ = rawValue;
              break;
            }
            case 16: {

              node_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 32: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bitty.proto.Broker.internal_static_com_bitty_proto_signupNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bitty.proto.Broker.internal_static_com_bitty_proto_signupNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bitty.proto.Broker.signupNode.class, com.bitty.proto.Broker.signupNode.Builder.class);
    }

    /**
     * Protobuf enum {@code com.bitty.proto.signupNode.Schema}
     */
    public enum Schema
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TCP = 0;</code>
       */
      TCP(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TCP = 0;</code>
       */
      public static final int TCP_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Schema valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Schema forNumber(int value) {
        switch (value) {
          case 0: return TCP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Schema>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Schema> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Schema>() {
              public Schema findValueByNumber(int number) {
                return Schema.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.bitty.proto.Broker.signupNode.getDescriptor().getEnumTypes().get(0);
      }

      private static final Schema[] VALUES = values();

      public static Schema valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Schema(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.bitty.proto.signupNode.Schema)
    }

    public static final int SCHEMA_FIELD_NUMBER = 1;
    private int schema_;
    /**
     * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
     * @return The enum numeric value on the wire for schema.
     */
    public int getSchemaValue() {
      return schema_;
    }
    /**
     * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
     * @return The schema.
     */
    public com.bitty.proto.Broker.signupNode.Schema getSchema() {
      @SuppressWarnings("deprecation")
      com.bitty.proto.Broker.signupNode.Schema result = com.bitty.proto.Broker.signupNode.Schema.valueOf(schema_);
      return result == null ? com.bitty.proto.Broker.signupNode.Schema.UNRECOGNIZED : result;
    }

    public static final int NODE_FIELD_NUMBER = 2;
    private int node_;
    /**
     * <code>int32 node = 2;</code>
     * @return The node.
     */
    public int getNode() {
      return node_;
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (schema_ != com.bitty.proto.Broker.signupNode.Schema.TCP.getNumber()) {
        output.writeEnum(1, schema_);
      }
      if (node_ != 0) {
        output.writeInt32(2, node_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(4, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (schema_ != com.bitty.proto.Broker.signupNode.Schema.TCP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, schema_);
      }
      if (node_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, node_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bitty.proto.Broker.signupNode)) {
        return super.equals(obj);
      }
      com.bitty.proto.Broker.signupNode other = (com.bitty.proto.Broker.signupNode) obj;

      if (schema_ != other.schema_) return false;
      if (getNode()
          != other.getNode()) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + schema_;
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bitty.proto.Broker.signupNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Broker.signupNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.signupNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Broker.signupNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bitty.proto.Broker.signupNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *注册节点
     * </pre>
     *
     * Protobuf type {@code com.bitty.proto.signupNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bitty.proto.signupNode)
        com.bitty.proto.Broker.signupNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_signupNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_signupNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bitty.proto.Broker.signupNode.class, com.bitty.proto.Broker.signupNode.Builder.class);
      }

      // Construct using com.bitty.proto.Broker.signupNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schema_ = 0;

        node_ = 0;

        ip_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bitty.proto.Broker.internal_static_com_bitty_proto_signupNode_descriptor;
      }

      @java.lang.Override
      public com.bitty.proto.Broker.signupNode getDefaultInstanceForType() {
        return com.bitty.proto.Broker.signupNode.getDefaultInstance();
      }

      @java.lang.Override
      public com.bitty.proto.Broker.signupNode build() {
        com.bitty.proto.Broker.signupNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bitty.proto.Broker.signupNode buildPartial() {
        com.bitty.proto.Broker.signupNode result = new com.bitty.proto.Broker.signupNode(this);
        result.schema_ = schema_;
        result.node_ = node_;
        result.ip_ = ip_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bitty.proto.Broker.signupNode) {
          return mergeFrom((com.bitty.proto.Broker.signupNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bitty.proto.Broker.signupNode other) {
        if (other == com.bitty.proto.Broker.signupNode.getDefaultInstance()) return this;
        if (other.schema_ != 0) {
          setSchemaValue(other.getSchemaValue());
        }
        if (other.getNode() != 0) {
          setNode(other.getNode());
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bitty.proto.Broker.signupNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bitty.proto.Broker.signupNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int schema_ = 0;
      /**
       * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
       * @return The enum numeric value on the wire for schema.
       */
      public int getSchemaValue() {
        return schema_;
      }
      /**
       * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
       * @param value The enum numeric value on the wire for schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchemaValue(int value) {
        schema_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
       * @return The schema.
       */
      public com.bitty.proto.Broker.signupNode.Schema getSchema() {
        @SuppressWarnings("deprecation")
        com.bitty.proto.Broker.signupNode.Schema result = com.bitty.proto.Broker.signupNode.Schema.valueOf(schema_);
        return result == null ? com.bitty.proto.Broker.signupNode.Schema.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
       * @param value The schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchema(com.bitty.proto.Broker.signupNode.Schema value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        schema_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.signupNode.Schema schema = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSchema() {
        
        schema_ = 0;
        onChanged();
        return this;
      }

      private int node_ ;
      /**
       * <code>int32 node = 2;</code>
       * @return The node.
       */
      public int getNode() {
        return node_;
      }
      /**
       * <code>int32 node = 2;</code>
       * @param value The node to set.
       * @return This builder for chaining.
       */
      public Builder setNode(int value) {
        
        node_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 node = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNode() {
        
        node_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 3;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 4;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 4;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bitty.proto.signupNode)
    }

    // @@protoc_insertion_point(class_scope:com.bitty.proto.signupNode)
    private static final com.bitty.proto.Broker.signupNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bitty.proto.Broker.signupNode();
    }

    public static com.bitty.proto.Broker.signupNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<signupNode>
        PARSER = new com.google.protobuf.AbstractParser<signupNode>() {
      @java.lang.Override
      public signupNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new signupNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<signupNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<signupNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bitty.proto.Broker.signupNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bitty_proto_MessageFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bitty_proto_resolveNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bitty_proto_resolveNode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bitty_proto_signupNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bitty_proto_signupNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014broker.proto\022\017com.bitty.proto\"\346\001\n\014Mess" +
      "ageFrame\022\021\n\tisRequest\030\001 \001(\010\022.\n\003cmd\030\002 \001(\016" +
      "2!.com.bitty.proto.MessageFrame.Cmd\022\r\n\005r" +
      "eqId\030\003 \001(\005\022\017\n\007payload\030\004 \001(\014\"s\n\003Cmd\022\010\n\004PI" +
      "NG\020\000\022\t\n\005ERROR\020c\022\017\n\013resolveNode\020\001\022\017\n\013reso" +
      "lveUser\020\002\022\n\n\006status\020\003\022\010\n\004DOWN\020\004\022\006\n\002Up\020\005\022" +
      "\013\n\007Forward\020\006\022\n\n\006signup\020\007\"}\n\013resolveNode\022" +
      "3\n\006schema\030\001 \001(\0162#.com.bitty.proto.resolv" +
      "eNode.Schema\022\014\n\004node\030\002 \001(\005\022\n\n\002ip\030\003 \001(\t\022\014" +
      "\n\004port\030\004 \001(\005\"\021\n\006Schema\022\007\n\003TCP\020\000\"{\n\nsignu" +
      "pNode\0222\n\006schema\030\001 \001(\0162\".com.bitty.proto." +
      "signupNode.Schema\022\014\n\004node\030\002 \001(\005\022\n\n\002ip\030\003 " +
      "\001(\t\022\014\n\004port\030\004 \001(\005\"\021\n\006Schema\022\007\n\003TCP\020\000B\010B\006" +
      "Brokerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bitty_proto_MessageFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bitty_proto_MessageFrame_descriptor,
        new java.lang.String[] { "IsRequest", "Cmd", "ReqId", "Payload", });
    internal_static_com_bitty_proto_resolveNode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bitty_proto_resolveNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bitty_proto_resolveNode_descriptor,
        new java.lang.String[] { "Schema", "Node", "Ip", "Port", });
    internal_static_com_bitty_proto_signupNode_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bitty_proto_signupNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bitty_proto_signupNode_descriptor,
        new java.lang.String[] { "Schema", "Node", "Ip", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
