// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.bitty.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bitty.proto.MessageFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  消息id
     * </pre>
     *
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <pre>
     *  时间
     * </pre>
     *
     * <code>int32 createAt = 2;</code>
     * @return The createAt.
     */
    int getCreateAt();

    /**
     * <pre>
     *目标节点
     * </pre>
     *
     * <code>int32 targetNode = 3;</code>
     * @return The targetNode.
     */
    int getTargetNode();

    /**
     * <pre>
     *目标id
     * </pre>
     *
     * <code>int32 targetId = 4;</code>
     * @return The targetId.
     */
    int getTargetId();

    /**
     * <pre>
     *源id
     * </pre>
     *
     * <code>int32 sourceId = 5;</code>
     * @return The sourceId.
     */
    int getSourceId();

    /**
     * <pre>
     *源节点
     * </pre>
     *
     * <code>int32 sourceNode = 6;</code>
     * @return The sourceNode.
     */
    int getSourceNode();

    /**
     * <pre>
     *命令码
     * </pre>
     *
     * <code>bytes Cmd = 7;</code>
     * @return The cmd.
     */
    com.google.protobuf.ByteString getCmd();

    /**
     * <pre>
     *命令子类型
     * </pre>
     *
     * <code>bytes Type = 8;</code>
     * @return The type.
     */
    com.google.protobuf.ByteString getType();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The payload.
     */
    java.lang.String getPayload();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The bytes for payload.
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * Protobuf type {@code com.bitty.proto.MessageFrame}
   */
  public  static final class MessageFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bitty.proto.MessageFrame)
      MessageFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageFrame.newBuilder() to construct.
    private MessageFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageFrame() {
      cmd_ = com.google.protobuf.ByteString.EMPTY;
      type_ = com.google.protobuf.ByteString.EMPTY;
      payload_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageFrame();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageFrame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 16: {

              createAt_ = input.readInt32();
              break;
            }
            case 24: {

              targetNode_ = input.readInt32();
              break;
            }
            case 32: {

              targetId_ = input.readInt32();
              break;
            }
            case 40: {

              sourceId_ = input.readInt32();
              break;
            }
            case 48: {

              sourceNode_ = input.readInt32();
              break;
            }
            case 58: {

              cmd_ = input.readBytes();
              break;
            }
            case 66: {

              type_ = input.readBytes();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              payload_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bitty.proto.Message.MessageFrame.class, com.bitty.proto.Message.MessageFrame.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <pre>
     *  消息id
     * </pre>
     *
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int CREATEAT_FIELD_NUMBER = 2;
    private int createAt_;
    /**
     * <pre>
     *  时间
     * </pre>
     *
     * <code>int32 createAt = 2;</code>
     * @return The createAt.
     */
    public int getCreateAt() {
      return createAt_;
    }

    public static final int TARGETNODE_FIELD_NUMBER = 3;
    private int targetNode_;
    /**
     * <pre>
     *目标节点
     * </pre>
     *
     * <code>int32 targetNode = 3;</code>
     * @return The targetNode.
     */
    public int getTargetNode() {
      return targetNode_;
    }

    public static final int TARGETID_FIELD_NUMBER = 4;
    private int targetId_;
    /**
     * <pre>
     *目标id
     * </pre>
     *
     * <code>int32 targetId = 4;</code>
     * @return The targetId.
     */
    public int getTargetId() {
      return targetId_;
    }

    public static final int SOURCEID_FIELD_NUMBER = 5;
    private int sourceId_;
    /**
     * <pre>
     *源id
     * </pre>
     *
     * <code>int32 sourceId = 5;</code>
     * @return The sourceId.
     */
    public int getSourceId() {
      return sourceId_;
    }

    public static final int SOURCENODE_FIELD_NUMBER = 6;
    private int sourceNode_;
    /**
     * <pre>
     *源节点
     * </pre>
     *
     * <code>int32 sourceNode = 6;</code>
     * @return The sourceNode.
     */
    public int getSourceNode() {
      return sourceNode_;
    }

    public static final int CMD_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString cmd_;
    /**
     * <pre>
     *命令码
     * </pre>
     *
     * <code>bytes Cmd = 7;</code>
     * @return The cmd.
     */
    public com.google.protobuf.ByteString getCmd() {
      return cmd_;
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString type_;
    /**
     * <pre>
     *命令子类型
     * </pre>
     *
     * <code>bytes Type = 8;</code>
     * @return The type.
     */
    public com.google.protobuf.ByteString getType() {
      return type_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 9;
    private volatile java.lang.Object payload_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The payload.
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The bytes for payload.
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (createAt_ != 0) {
        output.writeInt32(2, createAt_);
      }
      if (targetNode_ != 0) {
        output.writeInt32(3, targetNode_);
      }
      if (targetId_ != 0) {
        output.writeInt32(4, targetId_);
      }
      if (sourceId_ != 0) {
        output.writeInt32(5, sourceId_);
      }
      if (sourceNode_ != 0) {
        output.writeInt32(6, sourceNode_);
      }
      if (!cmd_.isEmpty()) {
        output.writeBytes(7, cmd_);
      }
      if (!type_.isEmpty()) {
        output.writeBytes(8, type_);
      }
      if (!getPayloadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (createAt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, createAt_);
      }
      if (targetNode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, targetNode_);
      }
      if (targetId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, targetId_);
      }
      if (sourceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sourceId_);
      }
      if (sourceNode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, sourceNode_);
      }
      if (!cmd_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, cmd_);
      }
      if (!type_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, type_);
      }
      if (!getPayloadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bitty.proto.Message.MessageFrame)) {
        return super.equals(obj);
      }
      com.bitty.proto.Message.MessageFrame other = (com.bitty.proto.Message.MessageFrame) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (getCreateAt()
          != other.getCreateAt()) return false;
      if (getTargetNode()
          != other.getTargetNode()) return false;
      if (getTargetId()
          != other.getTargetId()) return false;
      if (getSourceId()
          != other.getSourceId()) return false;
      if (getSourceNode()
          != other.getSourceNode()) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreateAt();
      hash = (37 * hash) + TARGETNODE_FIELD_NUMBER;
      hash = (53 * hash) + getTargetNode();
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetId();
      hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceId();
      hash = (37 * hash) + SOURCENODE_FIELD_NUMBER;
      hash = (53 * hash) + getSourceNode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bitty.proto.Message.MessageFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.MessageFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bitty.proto.Message.MessageFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bitty.proto.MessageFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bitty.proto.MessageFrame)
        com.bitty.proto.Message.MessageFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bitty.proto.Message.MessageFrame.class, com.bitty.proto.Message.MessageFrame.Builder.class);
      }

      // Construct using com.bitty.proto.Message.MessageFrame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        createAt_ = 0;

        targetNode_ = 0;

        targetId_ = 0;

        sourceId_ = 0;

        sourceNode_ = 0;

        cmd_ = com.google.protobuf.ByteString.EMPTY;

        type_ = com.google.protobuf.ByteString.EMPTY;

        payload_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_descriptor;
      }

      @java.lang.Override
      public com.bitty.proto.Message.MessageFrame getDefaultInstanceForType() {
        return com.bitty.proto.Message.MessageFrame.getDefaultInstance();
      }

      @java.lang.Override
      public com.bitty.proto.Message.MessageFrame build() {
        com.bitty.proto.Message.MessageFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bitty.proto.Message.MessageFrame buildPartial() {
        com.bitty.proto.Message.MessageFrame result = new com.bitty.proto.Message.MessageFrame(this);
        result.messageId_ = messageId_;
        result.createAt_ = createAt_;
        result.targetNode_ = targetNode_;
        result.targetId_ = targetId_;
        result.sourceId_ = sourceId_;
        result.sourceNode_ = sourceNode_;
        result.cmd_ = cmd_;
        result.type_ = type_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bitty.proto.Message.MessageFrame) {
          return mergeFrom((com.bitty.proto.Message.MessageFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bitty.proto.Message.MessageFrame other) {
        if (other == com.bitty.proto.Message.MessageFrame.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (other.getCreateAt() != 0) {
          setCreateAt(other.getCreateAt());
        }
        if (other.getTargetNode() != 0) {
          setTargetNode(other.getTargetNode());
        }
        if (other.getTargetId() != 0) {
          setTargetId(other.getTargetId());
        }
        if (other.getSourceId() != 0) {
          setSourceId(other.getSourceId());
        }
        if (other.getSourceNode() != 0) {
          setSourceNode(other.getSourceNode());
        }
        if (other.getCmd() != com.google.protobuf.ByteString.EMPTY) {
          setCmd(other.getCmd());
        }
        if (other.getType() != com.google.protobuf.ByteString.EMPTY) {
          setType(other.getType());
        }
        if (!other.getPayload().isEmpty()) {
          payload_ = other.payload_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bitty.proto.Message.MessageFrame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bitty.proto.Message.MessageFrame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <pre>
       *  消息id
       * </pre>
       *
       * <code>int32 messageId = 1;</code>
       * @return The messageId.
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <pre>
       *  消息id
       * </pre>
       *
       * <code>int32 messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  消息id
       * </pre>
       *
       * <code>int32 messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private int createAt_ ;
      /**
       * <pre>
       *  时间
       * </pre>
       *
       * <code>int32 createAt = 2;</code>
       * @return The createAt.
       */
      public int getCreateAt() {
        return createAt_;
      }
      /**
       * <pre>
       *  时间
       * </pre>
       *
       * <code>int32 createAt = 2;</code>
       * @param value The createAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreateAt(int value) {
        
        createAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  时间
       * </pre>
       *
       * <code>int32 createAt = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateAt() {
        
        createAt_ = 0;
        onChanged();
        return this;
      }

      private int targetNode_ ;
      /**
       * <pre>
       *目标节点
       * </pre>
       *
       * <code>int32 targetNode = 3;</code>
       * @return The targetNode.
       */
      public int getTargetNode() {
        return targetNode_;
      }
      /**
       * <pre>
       *目标节点
       * </pre>
       *
       * <code>int32 targetNode = 3;</code>
       * @param value The targetNode to set.
       * @return This builder for chaining.
       */
      public Builder setTargetNode(int value) {
        
        targetNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标节点
       * </pre>
       *
       * <code>int32 targetNode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetNode() {
        
        targetNode_ = 0;
        onChanged();
        return this;
      }

      private int targetId_ ;
      /**
       * <pre>
       *目标id
       * </pre>
       *
       * <code>int32 targetId = 4;</code>
       * @return The targetId.
       */
      public int getTargetId() {
        return targetId_;
      }
      /**
       * <pre>
       *目标id
       * </pre>
       *
       * <code>int32 targetId = 4;</code>
       * @param value The targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetId(int value) {
        
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标id
       * </pre>
       *
       * <code>int32 targetId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetId() {
        
        targetId_ = 0;
        onChanged();
        return this;
      }

      private int sourceId_ ;
      /**
       * <pre>
       *源id
       * </pre>
       *
       * <code>int32 sourceId = 5;</code>
       * @return The sourceId.
       */
      public int getSourceId() {
        return sourceId_;
      }
      /**
       * <pre>
       *源id
       * </pre>
       *
       * <code>int32 sourceId = 5;</code>
       * @param value The sourceId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceId(int value) {
        
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *源id
       * </pre>
       *
       * <code>int32 sourceId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceId() {
        
        sourceId_ = 0;
        onChanged();
        return this;
      }

      private int sourceNode_ ;
      /**
       * <pre>
       *源节点
       * </pre>
       *
       * <code>int32 sourceNode = 6;</code>
       * @return The sourceNode.
       */
      public int getSourceNode() {
        return sourceNode_;
      }
      /**
       * <pre>
       *源节点
       * </pre>
       *
       * <code>int32 sourceNode = 6;</code>
       * @param value The sourceNode to set.
       * @return This builder for chaining.
       */
      public Builder setSourceNode(int value) {
        
        sourceNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *源节点
       * </pre>
       *
       * <code>int32 sourceNode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceNode() {
        
        sourceNode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cmd_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>bytes Cmd = 7;</code>
       * @return The cmd.
       */
      public com.google.protobuf.ByteString getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>bytes Cmd = 7;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>bytes Cmd = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString type_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *命令子类型
       * </pre>
       *
       * <code>bytes Type = 8;</code>
       * @return The type.
       */
      public com.google.protobuf.ByteString getType() {
        return type_;
      }
      /**
       * <pre>
       *命令子类型
       * </pre>
       *
       * <code>bytes Type = 8;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令子类型
       * </pre>
       *
       * <code>bytes Type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }

      private java.lang.Object payload_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @return The payload.
       */
      public java.lang.String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @return The bytes for payload.
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        java.lang.Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @param value The bytes for payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payload_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bitty.proto.MessageFrame)
    }

    // @@protoc_insertion_point(class_scope:com.bitty.proto.MessageFrame)
    private static final com.bitty.proto.Message.MessageFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bitty.proto.Message.MessageFrame();
    }

    public static com.bitty.proto.Message.MessageFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageFrame>
        PARSER = new com.google.protobuf.AbstractParser<MessageFrame>() {
      @java.lang.Override
      public MessageFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageFrame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bitty.proto.Message.MessageFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bitty_proto_MessageFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\017com.bitty.proto\"\253\001\n\014Mes" +
      "sageFrame\022\021\n\tmessageId\030\001 \001(\005\022\020\n\010createAt" +
      "\030\002 \001(\005\022\022\n\ntargetNode\030\003 \001(\005\022\020\n\010targetId\030\004" +
      " \001(\005\022\020\n\010sourceId\030\005 \001(\005\022\022\n\nsourceNode\030\006 \001" +
      "(\005\022\013\n\003Cmd\030\007 \001(\014\022\014\n\004Type\030\010 \001(\014\022\017\n\007payload" +
      "\030\t \001(\tB\tB\007Messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bitty_proto_MessageFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bitty_proto_MessageFrame_descriptor,
        new java.lang.String[] { "MessageId", "CreateAt", "TargetNode", "TargetId", "SourceId", "SourceNode", "Cmd", "Type", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
