// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.bitty.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bitty.proto.MessageFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  消息id
     * </pre>
     *
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <pre>
     *  时间
     * </pre>
     *
     * <code>int32 createAt = 2;</code>
     * @return The createAt.
     */
    int getCreateAt();

    /**
     * <pre>
     *目标节点
     * </pre>
     *
     * <code>int32 targetNode = 3;</code>
     * @return The targetNode.
     */
    int getTargetNode();

    /**
     * <pre>
     *目标id
     * </pre>
     *
     * <code>int32 targetId = 4;</code>
     * @return The targetId.
     */
    int getTargetId();

    /**
     * <pre>
     *源id
     * </pre>
     *
     * <code>int32 sourceId = 5;</code>
     * @return The sourceId.
     */
    int getSourceId();

    /**
     * <pre>
     *源节点
     * </pre>
     *
     * <code>int32 sourceNode = 6;</code>
     * @return The sourceNode.
     */
    int getSourceNode();

    /**
     * <pre>
     *命令码
     * </pre>
     *
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    int getCmdValue();
    /**
     * <pre>
     *命令码
     * </pre>
     *
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
     * @return The cmd.
     */
    com.bitty.proto.Message.MessageFrame.Cmd getCmd();

    /**
     * <pre>
     *命令子类型
     * </pre>
     *
     * <code>bytes Type = 8;</code>
     * @return The type.
     */
    com.google.protobuf.ByteString getType();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code com.bitty.proto.MessageFrame}
   */
  public  static final class MessageFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bitty.proto.MessageFrame)
      MessageFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageFrame.newBuilder() to construct.
    private MessageFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageFrame() {
      cmd_ = 0;
      type_ = com.google.protobuf.ByteString.EMPTY;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageFrame();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageFrame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 16: {

              createAt_ = input.readInt32();
              break;
            }
            case 24: {

              targetNode_ = input.readInt32();
              break;
            }
            case 32: {

              targetId_ = input.readInt32();
              break;
            }
            case 40: {

              sourceId_ = input.readInt32();
              break;
            }
            case 48: {

              sourceNode_ = input.readInt32();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 66: {

              type_ = input.readBytes();
              break;
            }
            case 74: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bitty.proto.Message.MessageFrame.class, com.bitty.proto.Message.MessageFrame.Builder.class);
    }

    /**
     * <pre>
     *设备命令码
     * </pre>
     *
     * Protobuf enum {@code com.bitty.proto.MessageFrame.Cmd}
     */
    public enum Cmd
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      /**
       * <code>ERROR = 99;</code>
       */
      ERROR(99),
      /**
       * <code>OK = 100;</code>
       */
      OK(100),
      /**
       * <pre>
       **
       *鉴权
       * </pre>
       *
       * <code>AUTH = 1;</code>
       */
      AUTH(1),
      /**
       * <pre>
       **
       *发送消息
       * </pre>
       *
       * <code>MESSAGE = 2;</code>
       */
      MESSAGE(2),
      /**
       * <pre>
       **
       *同步消息
       * </pre>
       *
       * <code>SYNC = 3;</code>
       */
      SYNC(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;
      /**
       * <code>ERROR = 99;</code>
       */
      public static final int ERROR_VALUE = 99;
      /**
       * <code>OK = 100;</code>
       */
      public static final int OK_VALUE = 100;
      /**
       * <pre>
       **
       *鉴权
       * </pre>
       *
       * <code>AUTH = 1;</code>
       */
      public static final int AUTH_VALUE = 1;
      /**
       * <pre>
       **
       *发送消息
       * </pre>
       *
       * <code>MESSAGE = 2;</code>
       */
      public static final int MESSAGE_VALUE = 2;
      /**
       * <pre>
       **
       *同步消息
       * </pre>
       *
       * <code>SYNC = 3;</code>
       */
      public static final int SYNC_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Cmd valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Cmd forNumber(int value) {
        switch (value) {
          case 0: return PING;
          case 99: return ERROR;
          case 100: return OK;
          case 1: return AUTH;
          case 2: return MESSAGE;
          case 3: return SYNC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Cmd> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
              public Cmd findValueByNumber(int number) {
                return Cmd.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.bitty.proto.Message.MessageFrame.getDescriptor().getEnumTypes().get(0);
      }

      private static final Cmd[] VALUES = values();

      public static Cmd valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Cmd(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.bitty.proto.MessageFrame.Cmd)
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <pre>
     *  消息id
     * </pre>
     *
     * <code>int32 messageId = 1;</code>
     * @return The messageId.
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int CREATEAT_FIELD_NUMBER = 2;
    private int createAt_;
    /**
     * <pre>
     *  时间
     * </pre>
     *
     * <code>int32 createAt = 2;</code>
     * @return The createAt.
     */
    public int getCreateAt() {
      return createAt_;
    }

    public static final int TARGETNODE_FIELD_NUMBER = 3;
    private int targetNode_;
    /**
     * <pre>
     *目标节点
     * </pre>
     *
     * <code>int32 targetNode = 3;</code>
     * @return The targetNode.
     */
    public int getTargetNode() {
      return targetNode_;
    }

    public static final int TARGETID_FIELD_NUMBER = 4;
    private int targetId_;
    /**
     * <pre>
     *目标id
     * </pre>
     *
     * <code>int32 targetId = 4;</code>
     * @return The targetId.
     */
    public int getTargetId() {
      return targetId_;
    }

    public static final int SOURCEID_FIELD_NUMBER = 5;
    private int sourceId_;
    /**
     * <pre>
     *源id
     * </pre>
     *
     * <code>int32 sourceId = 5;</code>
     * @return The sourceId.
     */
    public int getSourceId() {
      return sourceId_;
    }

    public static final int SOURCENODE_FIELD_NUMBER = 6;
    private int sourceNode_;
    /**
     * <pre>
     *源节点
     * </pre>
     *
     * <code>int32 sourceNode = 6;</code>
     * @return The sourceNode.
     */
    public int getSourceNode() {
      return sourceNode_;
    }

    public static final int CMD_FIELD_NUMBER = 7;
    private int cmd_;
    /**
     * <pre>
     *命令码
     * </pre>
     *
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <pre>
     *命令码
     * </pre>
     *
     * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
     * @return The cmd.
     */
    public com.bitty.proto.Message.MessageFrame.Cmd getCmd() {
      @SuppressWarnings("deprecation")
      com.bitty.proto.Message.MessageFrame.Cmd result = com.bitty.proto.Message.MessageFrame.Cmd.valueOf(cmd_);
      return result == null ? com.bitty.proto.Message.MessageFrame.Cmd.UNRECOGNIZED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString type_;
    /**
     * <pre>
     *命令子类型
     * </pre>
     *
     * <code>bytes Type = 8;</code>
     * @return The type.
     */
    public com.google.protobuf.ByteString getType() {
      return type_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString payload_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @return The payload.
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (createAt_ != 0) {
        output.writeInt32(2, createAt_);
      }
      if (targetNode_ != 0) {
        output.writeInt32(3, targetNode_);
      }
      if (targetId_ != 0) {
        output.writeInt32(4, targetId_);
      }
      if (sourceId_ != 0) {
        output.writeInt32(5, sourceId_);
      }
      if (sourceNode_ != 0) {
        output.writeInt32(6, sourceNode_);
      }
      if (cmd_ != com.bitty.proto.Message.MessageFrame.Cmd.PING.getNumber()) {
        output.writeEnum(7, cmd_);
      }
      if (!type_.isEmpty()) {
        output.writeBytes(8, type_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(9, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (createAt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, createAt_);
      }
      if (targetNode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, targetNode_);
      }
      if (targetId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, targetId_);
      }
      if (sourceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sourceId_);
      }
      if (sourceNode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, sourceNode_);
      }
      if (cmd_ != com.bitty.proto.Message.MessageFrame.Cmd.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, cmd_);
      }
      if (!type_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, type_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bitty.proto.Message.MessageFrame)) {
        return super.equals(obj);
      }
      com.bitty.proto.Message.MessageFrame other = (com.bitty.proto.Message.MessageFrame) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (getCreateAt()
          != other.getCreateAt()) return false;
      if (getTargetNode()
          != other.getTargetNode()) return false;
      if (getTargetId()
          != other.getTargetId()) return false;
      if (getSourceId()
          != other.getSourceId()) return false;
      if (getSourceNode()
          != other.getSourceNode()) return false;
      if (cmd_ != other.cmd_) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreateAt();
      hash = (37 * hash) + TARGETNODE_FIELD_NUMBER;
      hash = (53 * hash) + getTargetNode();
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetId();
      hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceId();
      hash = (37 * hash) + SOURCENODE_FIELD_NUMBER;
      hash = (53 * hash) + getSourceNode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bitty.proto.Message.MessageFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.MessageFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.MessageFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bitty.proto.Message.MessageFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bitty.proto.MessageFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bitty.proto.MessageFrame)
        com.bitty.proto.Message.MessageFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bitty.proto.Message.MessageFrame.class, com.bitty.proto.Message.MessageFrame.Builder.class);
      }

      // Construct using com.bitty.proto.Message.MessageFrame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        createAt_ = 0;

        targetNode_ = 0;

        targetId_ = 0;

        sourceId_ = 0;

        sourceNode_ = 0;

        cmd_ = 0;

        type_ = com.google.protobuf.ByteString.EMPTY;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_MessageFrame_descriptor;
      }

      @java.lang.Override
      public com.bitty.proto.Message.MessageFrame getDefaultInstanceForType() {
        return com.bitty.proto.Message.MessageFrame.getDefaultInstance();
      }

      @java.lang.Override
      public com.bitty.proto.Message.MessageFrame build() {
        com.bitty.proto.Message.MessageFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bitty.proto.Message.MessageFrame buildPartial() {
        com.bitty.proto.Message.MessageFrame result = new com.bitty.proto.Message.MessageFrame(this);
        result.messageId_ = messageId_;
        result.createAt_ = createAt_;
        result.targetNode_ = targetNode_;
        result.targetId_ = targetId_;
        result.sourceId_ = sourceId_;
        result.sourceNode_ = sourceNode_;
        result.cmd_ = cmd_;
        result.type_ = type_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bitty.proto.Message.MessageFrame) {
          return mergeFrom((com.bitty.proto.Message.MessageFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bitty.proto.Message.MessageFrame other) {
        if (other == com.bitty.proto.Message.MessageFrame.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (other.getCreateAt() != 0) {
          setCreateAt(other.getCreateAt());
        }
        if (other.getTargetNode() != 0) {
          setTargetNode(other.getTargetNode());
        }
        if (other.getTargetId() != 0) {
          setTargetId(other.getTargetId());
        }
        if (other.getSourceId() != 0) {
          setSourceId(other.getSourceId());
        }
        if (other.getSourceNode() != 0) {
          setSourceNode(other.getSourceNode());
        }
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (other.getType() != com.google.protobuf.ByteString.EMPTY) {
          setType(other.getType());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bitty.proto.Message.MessageFrame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bitty.proto.Message.MessageFrame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <pre>
       *  消息id
       * </pre>
       *
       * <code>int32 messageId = 1;</code>
       * @return The messageId.
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <pre>
       *  消息id
       * </pre>
       *
       * <code>int32 messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  消息id
       * </pre>
       *
       * <code>int32 messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private int createAt_ ;
      /**
       * <pre>
       *  时间
       * </pre>
       *
       * <code>int32 createAt = 2;</code>
       * @return The createAt.
       */
      public int getCreateAt() {
        return createAt_;
      }
      /**
       * <pre>
       *  时间
       * </pre>
       *
       * <code>int32 createAt = 2;</code>
       * @param value The createAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreateAt(int value) {
        
        createAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  时间
       * </pre>
       *
       * <code>int32 createAt = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateAt() {
        
        createAt_ = 0;
        onChanged();
        return this;
      }

      private int targetNode_ ;
      /**
       * <pre>
       *目标节点
       * </pre>
       *
       * <code>int32 targetNode = 3;</code>
       * @return The targetNode.
       */
      public int getTargetNode() {
        return targetNode_;
      }
      /**
       * <pre>
       *目标节点
       * </pre>
       *
       * <code>int32 targetNode = 3;</code>
       * @param value The targetNode to set.
       * @return This builder for chaining.
       */
      public Builder setTargetNode(int value) {
        
        targetNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标节点
       * </pre>
       *
       * <code>int32 targetNode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetNode() {
        
        targetNode_ = 0;
        onChanged();
        return this;
      }

      private int targetId_ ;
      /**
       * <pre>
       *目标id
       * </pre>
       *
       * <code>int32 targetId = 4;</code>
       * @return The targetId.
       */
      public int getTargetId() {
        return targetId_;
      }
      /**
       * <pre>
       *目标id
       * </pre>
       *
       * <code>int32 targetId = 4;</code>
       * @param value The targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetId(int value) {
        
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标id
       * </pre>
       *
       * <code>int32 targetId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetId() {
        
        targetId_ = 0;
        onChanged();
        return this;
      }

      private int sourceId_ ;
      /**
       * <pre>
       *源id
       * </pre>
       *
       * <code>int32 sourceId = 5;</code>
       * @return The sourceId.
       */
      public int getSourceId() {
        return sourceId_;
      }
      /**
       * <pre>
       *源id
       * </pre>
       *
       * <code>int32 sourceId = 5;</code>
       * @param value The sourceId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceId(int value) {
        
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *源id
       * </pre>
       *
       * <code>int32 sourceId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceId() {
        
        sourceId_ = 0;
        onChanged();
        return this;
      }

      private int sourceNode_ ;
      /**
       * <pre>
       *源节点
       * </pre>
       *
       * <code>int32 sourceNode = 6;</code>
       * @return The sourceNode.
       */
      public int getSourceNode() {
        return sourceNode_;
      }
      /**
       * <pre>
       *源节点
       * </pre>
       *
       * <code>int32 sourceNode = 6;</code>
       * @param value The sourceNode to set.
       * @return This builder for chaining.
       */
      public Builder setSourceNode(int value) {
        
        sourceNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *源节点
       * </pre>
       *
       * <code>int32 sourceNode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceNode() {
        
        sourceNode_ = 0;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
       * @return The enum numeric value on the wire for cmd.
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
       * @param value The enum numeric value on the wire for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
       * @return The cmd.
       */
      public com.bitty.proto.Message.MessageFrame.Cmd getCmd() {
        @SuppressWarnings("deprecation")
        com.bitty.proto.Message.MessageFrame.Cmd result = com.bitty.proto.Message.MessageFrame.Cmd.valueOf(cmd_);
        return result == null ? com.bitty.proto.Message.MessageFrame.Cmd.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.bitty.proto.Message.MessageFrame.Cmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令码
       * </pre>
       *
       * <code>.com.bitty.proto.MessageFrame.Cmd cmd = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString type_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *命令子类型
       * </pre>
       *
       * <code>bytes Type = 8;</code>
       * @return The type.
       */
      public com.google.protobuf.ByteString getType() {
        return type_;
      }
      /**
       * <pre>
       *命令子类型
       * </pre>
       *
       * <code>bytes Type = 8;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令子类型
       * </pre>
       *
       * <code>bytes Type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>bytes payload = 9;</code>
       * @return The payload.
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>bytes payload = 9;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>bytes payload = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bitty.proto.MessageFrame)
    }

    // @@protoc_insertion_point(class_scope:com.bitty.proto.MessageFrame)
    private static final com.bitty.proto.Message.MessageFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bitty.proto.Message.MessageFrame();
    }

    public static com.bitty.proto.Message.MessageFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageFrame>
        PARSER = new com.google.protobuf.AbstractParser<MessageFrame>() {
      @java.lang.Override
      public MessageFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageFrame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bitty.proto.Message.MessageFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bitty.proto.Auth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
     * @return The enum numeric value on the wire for schema.
     */
    int getSchemaValue();
    /**
     * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
     * @return The schema.
     */
    com.bitty.proto.Message.Auth.Schema getSchema();

    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code com.bitty.proto.Auth}
   */
  public  static final class Auth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bitty.proto.Auth)
      AuthOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Auth.newBuilder() to construct.
    private Auth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Auth() {
      schema_ = 0;
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Auth();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Auth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              schema_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bitty.proto.Message.internal_static_com_bitty_proto_Auth_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bitty.proto.Message.internal_static_com_bitty_proto_Auth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bitty.proto.Message.Auth.class, com.bitty.proto.Message.Auth.Builder.class);
    }

    /**
     * Protobuf enum {@code com.bitty.proto.Auth.Schema}
     */
    public enum Schema
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TCP = 0;</code>
       */
      TCP(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TCP = 0;</code>
       */
      public static final int TCP_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Schema valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Schema forNumber(int value) {
        switch (value) {
          case 0: return TCP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Schema>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Schema> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Schema>() {
              public Schema findValueByNumber(int number) {
                return Schema.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.bitty.proto.Message.Auth.getDescriptor().getEnumTypes().get(0);
      }

      private static final Schema[] VALUES = values();

      public static Schema valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Schema(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.bitty.proto.Auth.Schema)
    }

    public static final int SCHEMA_FIELD_NUMBER = 1;
    private int schema_;
    /**
     * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
     * @return The enum numeric value on the wire for schema.
     */
    public int getSchemaValue() {
      return schema_;
    }
    /**
     * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
     * @return The schema.
     */
    public com.bitty.proto.Message.Auth.Schema getSchema() {
      @SuppressWarnings("deprecation")
      com.bitty.proto.Message.Auth.Schema result = com.bitty.proto.Message.Auth.Schema.valueOf(schema_);
      return result == null ? com.bitty.proto.Message.Auth.Schema.UNRECOGNIZED : result;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (schema_ != com.bitty.proto.Message.Auth.Schema.TCP.getNumber()) {
        output.writeEnum(1, schema_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (schema_ != com.bitty.proto.Message.Auth.Schema.TCP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, schema_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bitty.proto.Message.Auth)) {
        return super.equals(obj);
      }
      com.bitty.proto.Message.Auth other = (com.bitty.proto.Message.Auth) obj;

      if (schema_ != other.schema_) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + schema_;
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bitty.proto.Message.Auth parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.Auth parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.Auth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.Auth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.Auth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bitty.proto.Message.Auth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bitty.proto.Message.Auth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.Auth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Message.Auth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.Auth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bitty.proto.Message.Auth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bitty.proto.Message.Auth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bitty.proto.Message.Auth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bitty.proto.Auth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bitty.proto.Auth)
        com.bitty.proto.Message.AuthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_Auth_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_Auth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bitty.proto.Message.Auth.class, com.bitty.proto.Message.Auth.Builder.class);
      }

      // Construct using com.bitty.proto.Message.Auth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schema_ = 0;

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bitty.proto.Message.internal_static_com_bitty_proto_Auth_descriptor;
      }

      @java.lang.Override
      public com.bitty.proto.Message.Auth getDefaultInstanceForType() {
        return com.bitty.proto.Message.Auth.getDefaultInstance();
      }

      @java.lang.Override
      public com.bitty.proto.Message.Auth build() {
        com.bitty.proto.Message.Auth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bitty.proto.Message.Auth buildPartial() {
        com.bitty.proto.Message.Auth result = new com.bitty.proto.Message.Auth(this);
        result.schema_ = schema_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bitty.proto.Message.Auth) {
          return mergeFrom((com.bitty.proto.Message.Auth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bitty.proto.Message.Auth other) {
        if (other == com.bitty.proto.Message.Auth.getDefaultInstance()) return this;
        if (other.schema_ != 0) {
          setSchemaValue(other.getSchemaValue());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bitty.proto.Message.Auth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bitty.proto.Message.Auth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int schema_ = 0;
      /**
       * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
       * @return The enum numeric value on the wire for schema.
       */
      public int getSchemaValue() {
        return schema_;
      }
      /**
       * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
       * @param value The enum numeric value on the wire for schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchemaValue(int value) {
        schema_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
       * @return The schema.
       */
      public com.bitty.proto.Message.Auth.Schema getSchema() {
        @SuppressWarnings("deprecation")
        com.bitty.proto.Message.Auth.Schema result = com.bitty.proto.Message.Auth.Schema.valueOf(schema_);
        return result == null ? com.bitty.proto.Message.Auth.Schema.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
       * @param value The schema to set.
       * @return This builder for chaining.
       */
      public Builder setSchema(com.bitty.proto.Message.Auth.Schema value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        schema_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.bitty.proto.Auth.Schema schema = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSchema() {
        
        schema_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bitty.proto.Auth)
    }

    // @@protoc_insertion_point(class_scope:com.bitty.proto.Auth)
    private static final com.bitty.proto.Message.Auth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bitty.proto.Message.Auth();
    }

    public static com.bitty.proto.Message.Auth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Auth>
        PARSER = new com.google.protobuf.AbstractParser<Auth>() {
      @java.lang.Override
      public Auth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Auth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Auth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Auth> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bitty.proto.Message.Auth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bitty_proto_MessageFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bitty_proto_Auth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bitty_proto_Auth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\017com.bitty.proto\"\223\002\n\014Mes" +
      "sageFrame\022\021\n\tmessageId\030\001 \001(\005\022\020\n\010createAt" +
      "\030\002 \001(\005\022\022\n\ntargetNode\030\003 \001(\005\022\020\n\010targetId\030\004" +
      " \001(\005\022\020\n\010sourceId\030\005 \001(\005\022\022\n\nsourceNode\030\006 \001" +
      "(\005\022.\n\003cmd\030\007 \001(\0162!.com.bitty.proto.Messag" +
      "eFrame.Cmd\022\014\n\004Type\030\010 \001(\014\022\017\n\007payload\030\t \001(" +
      "\014\"C\n\003Cmd\022\010\n\004PING\020\000\022\t\n\005ERROR\020c\022\006\n\002OK\020d\022\010\n" +
      "\004AUTH\020\001\022\013\n\007MESSAGE\020\002\022\010\n\004SYNC\020\003\"V\n\004Auth\022," +
      "\n\006schema\030\001 \001(\0162\034.com.bitty.proto.Auth.Sc" +
      "hema\022\r\n\005token\030\002 \001(\t\"\021\n\006Schema\022\007\n\003TCP\020\000B\t" +
      "B\007Messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bitty_proto_MessageFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bitty_proto_MessageFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bitty_proto_MessageFrame_descriptor,
        new java.lang.String[] { "MessageId", "CreateAt", "TargetNode", "TargetId", "SourceId", "SourceNode", "Cmd", "Type", "Payload", });
    internal_static_com_bitty_proto_Auth_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bitty_proto_Auth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bitty_proto_Auth_descriptor,
        new java.lang.String[] { "Schema", "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
